global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus-ticket
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus-ticket:9090
    labels:
      application: 'prometheus-ticket'
- job_name: catalogo-api
  metrics_path: /metrics
  static_configs:
  - targets:
    - catalogo-api:8080
    labels: 
      application: 'catalogo-api'

