name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: jtony.net@gmail.com
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.1
      with:
        name: cine-catalogo-api         

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile.CI
        push: true
        tags: jtonynet/cine-catalogo:latest
        # tags: jtonynet/cine-catalogo:${{ github.ref_name }}
