name: TESTES_CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        go_version: ['1.21.1', '>=1.21.6']
#        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
         go-version: 1.21.1
#        go-version: ${{ matrix.go_version }}

    - name: Build-DB
      run: docker compose build postgres-catalogo
      
    - name: Create-DB
      run: docker compose up postgres-catalogo -d
      
    - name: Wait for DB to start
      run: sleep 5
      
    - name: Test
      run: go test -v main_happy_path_smoke_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v cmd/api/main.go
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.1.0
      with:
        name: cine-catalogo-api
        path: main 

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

